### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Hoxolotl**
updated the shell script with:
    --volume "${PWD}/assets:/var/www/html/assets" \
and 
    --publish-all   \

### CODE REVIEW

**Comment by Potherca** [comment]
Uhm... _which_ shell script?

**Comment by Potherca** [comment]
Ah, I think I found it! You mean in the README?

https://github.com/SimplyEdit/simplycode-docker/blob/main/README.md?plain=1#L31-L38

```
docker run \
    --env "USER_GID=$(id -g)" \
    --env "USER_ID=$(id -u)" \
    --interactive \
    --rm \
    --tty \
    --volume "${PWD}:/var/www/www/api/data" \
    ghcr.io/simplyedit/simplycode-docker:main
```

**Comment by Hoxolotl** [comment]
Yes I meant in the readme :)

**Comment by Potherca** [comment]
The `--publish-all` _is_ already mentioned... It might not be desirable to use that always, TBH.

As for the `--volume "${PWD}/assets:/var/www/html/assets"` what is it that is being mounted? And/Or what is missing now?

**Comment by Potherca** [comment]
I think I tracked this back to the bash "launcher" for docker in https://github.com/SimplyEdit/simplycode/.

I'll ask @ylebre regarding the assets. 

Also, I did a cleanup:  https://github.com/SimplyEdit/simplycode/pull/31. If so desired, we _could_ add a check here to make sure both script and command in the README continue to be the same? (Might be overkill, not sure...)

**Comment by Hoxolotl** [comment]
Ask Ylebre, he was the one who gave me that over slack, I just copy-paste-used it.

**Comment by Potherca** [comment]
The reason that `assets` has been added, is for those cases where the developer has assets (JS, CSS, images file, etc.) they want to use in their app. It is currently considered a short-term solution/hack until a thorough, long-term solution has been decided upon.

So for now, best to leave it out.

**Comment by Potherca** [comment]
The two questions are :

1. **Should we add `--publish-all` to the default example?**<br> I am inclined to say "no" as I would rather not teach a bad practice to people who do not know what it means. As it is already mentioned for the specific use-case I am inclined to leave this as-as.
2. **Should we add `--volume "${PWD}/assets:/var/www/html/assets"` to the deafult example?**<br>Here, I also think "no" BUT it might be worth adding some prose explaining that this _can_ be done (and why, i.e. which use-case it solves for now).

**Comment by Potherca** [comment]
Closing for now.

**Pull request closed without merging**
